Fix "Unknown directive.. directory" error.
When using "upgrade-step:directory", the ``meta.zcm`` of ``ftw.upgrade`` must be loaded first.
This may be done automatically because of z3c.autoinclude, but is in fact random.

Otherwise this error may occur:
```
ZopeXMLConfigurationError: File "/var/lib/jenkins/jobs/wetzikon.policy-master-test-plone-4.3.2.cfg/workspace/src/ftw.shop/ftw/shop/configure.zcml", line 53.4
ConfigurationError: ('Unknown directive', u'http://namespaces.zope.org/ftw.upgrade', u'directory')
```